services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "eds"
      POSTGRES_DB: "eds"
    volumes:
      - "./assets/sql/init.sql:/docker-entrypoint-initdb.d/init.sql"

    ports:
      - "5432:5432"